### ISSUE TITLE
Click at the start of sound - continued.

### ISSUE THREAD

**Issue by vnams** [surikov/webaudiofont#105]
Thanks for the quick reply.

Yes, that example does not have clicks. So, it must be something that I'm doing. But, this happens with all of the samples that I've tried, no matter what the source or what type of editing I'm doing. So it must be something wrong in my process. 
Can you check this out? 
files:
cello F#5.wav is the sample file
CustomInstrument.js contains the custom instrument I made from it.
temp1.html plays the sound.

Can you hear the click at the start? 

[files.zip](https://github.com/surikov/webaudiofont/files/14149414/files.zip)

**Comment by surikov** [comment]
[fixed.zip](https://github.com/surikov/webaudiofont/files/14150080/fixed.zip)

donwload and listen fixed instrument.
it works without clicks

use 'file' instead of 'sample' in CustomInstrument.js
copy-paste Base64 data carefully
use Audacity to convert a sound to mp3 and ogg
use Audacity timescale to find a right values for loopStart and loopEnd

Keep in mind that audio editing is a difficult task
