### ISSUE TITLE
[Question] Can I use your example/MIDIFile.js for midi loading in my project ?

### ISSUE THREAD

**Issue by yw662** [surikov/webaudiofont#22]
I previously use tone.js for music play and tonjs/MIDIConvert for MIDI loading.

But it seems that there some differences between WebAudioFont and tone.js, and it seems that, your example/MIDIFile.js is more convenient whe =n using WebAudioFont.

But it seems that, MIDIFile.js is only for example purpose.
So, can I use it, and is it also under MIT license ?

**Comment by surikov** [comment]
Look to https://github.com/nfroidure/midifile
for information about MIDIFile.js

**Comment by cperezvinsite** [comment]
I installed midifile as you suggest, but this library does not has the method parseSong, did you use a custom release or something?

**Comment by camiloperezv** [comment]
I installed midifile as you suggest using npm, but this library does not has the method parseSong, did you use a custom release or something?

**Comment by surikov** [comment]
I didn't suggest you install midifile.

Look to source of examples.

**Comment by camiloperezv** [comment]
I was looking https://surikov.github.io/webaudiofont/examples/midiplayer.html# This example loads a file using midiFile module.

> Look to https://github.com/nfroidure/midifile

But the midifile you use there is different to the github midifile, because of the parseSong.

I looked into the `nfroidure/midifile` and didn't find the `parseSong` function.

The code is 
```javascript

var arrayBuffer = xmlHttpRequest.response;
var midiFile = new MIDIFile(arrayBuffer);
var song = midiFile.parseSong();
startLoad(song);


```
There is any example of this library which uses the raw MIDIFile loaded by `var midiFile = new MIDIFile(arrayBuffer);` and not using `midiFile.parseSong();`

**Comment by surikov** [comment]
I don't support https://github.com/nfroidure/midifile
WebAudioFont is the sound library but not a MIDI library.

Write your own parsing routine or copy it from my example. This is very small piece of code.
