### ISSUE TITLE
about custom sample

### ISSUE THREAD

**Issue by WarpPrism** [surikov/webaudiofont#49]
Hello, I have followed the tutorial about custom sample and make a sound sample file. But it's very hard to do that. What's more, the sample I made has a great difference with my audio source.

Are there some auto-tools for making custom sample js file?  I can't imagine that all instruments in the catalog are made by hand.

my email adress is 249662605@qq.com

hope your reply.

**Comment by surikov** [comment]
Sound converter isn't available for public yet.

**Comment by WarpPrism** [comment]
OK, I undstand. What if I send my sample source by email. You convert them for me? You can also add these sample to the catalog. Thanks for your help.

**Comment by surikov** [comment]
Do you really think your samples are better than existed pianos?

I investigated thousand of samples to select 88 pianos to meet any needs. There are small samples with low quality to reduce download time and big samples to create good sound.
For example WebAudioFont already consists of samples opensource Fluid soundfont that has a huge size. 

Please listen instruments and choose a piano that sound good for you.

Creating of good custom samples is a very complex work. You need to define properly loop points, zones, etc. You need adjust volume to average value, define frequency filters, etc.  Otherwise your sample will sound good as single sound but sounds bad togever with other instruments.
Due of this the most of free samples in internet are copy of old professional libraries from Roland or Creative.

**Comment by surikov** [comment]
I looked to your https://www.autopiano.cn/

The app plays sound with clicks at end of button clicks.
The app doesn't use reverberation.

Look to WebAudioFont examples to learn how to fix those problems.

You don't need better audio samples. You need to improve your player.
