### ISSUE TITLE
Transport

### ISSUE THREAD

**Issue by sjmartin** [surikov/webaudiofont#51]
Tone.js features a Transport object that controls a “playback head” for triggering pre-scheduled single events (e.g. triggering a note to play). The object features functions such as play, pause, rewind. My question: does WebAudio Font feature an equivalent Transport facility? If so, please can you give me an introduction to using it or point me in the direction of documentation for its use. Many thanks, and congratulations on such a great product.

**Comment by surikov** [comment]
Every parameter of AudioNode already implements scheduling of changes. You don't need 'transport' object because Web Audio API implements it by origin.

See https://developer.mozilla.org/en-US/docs/Web/API/AudioParam

You can schedule notes to play them at any time, see description https://github.com/surikov/webaudiofont/wiki/2.1.-queueWaveTable

See example https://surikov.github.io/webaudiofont/examples/realtime.html

**Comment by stephaneeybert** [comment]
@surikov  Zdrasvouitie Sergei :-) Kak u vas dila ? 

I've been trying to use your web audio font in my Angular app but could not get it. I struggled and failed.

You know some who had more success than me ? 

For now, I'm using a very simple Tone.js synth as in:
```
    const synth: any = new Tone.PolySynth(8, Tone.Synth, {
      oscillator: {
        partials: [0, 2, 3, 4]
      }
    }).toMaster();

```
I was hoping to use some of the timbres you created.

**Comment by surikov** [comment]
Please ask Tone.js team about Tone.js

Use WebAudioFont for musical applictions.

You don't need Tone.js for music apps. Moreover, Tone.js isn't enough for musical apps like this example
https://surikov.github.io/webaudiofont/examples/mixer.html
